#!/usr/bin/env python3
"""
Cost estimator for Ensemble, the personal cross-functional dev team.

Usage:
    python3 estimate_cost.py <model> <input_tokens> <output_tokens> [--cached]

    model:          haiku | sonnet | opus
    input_tokens:   tokens sent to the model this call
    output_tokens:  tokens generated by the model this call
    --cached:       treat input_tokens as a cache read instead of a fresh read
                    (roughly 5-20x cheaper depending on model; see cost_rates.json)

Or import estimate() / summarize() from another script to total up a whole
pipeline run (one call per stage: triage, architect, developer, tester, deployer).

This is a rough estimator for deciding where a pipeline's money is going, not a
billing tool -- always check the Console for actual spend.
"""
import json
import sys
from pathlib import Path

RATES_PATH = Path(__file__).parent / "cost_rates.json"


def load_rates():
    with open(RATES_PATH) as f:
        return json.load(f)


def estimate(model: str, input_tokens: int, output_tokens: int, cached: bool = False) -> float:
    rates = load_rates()
    model = model.lower()
    if model not in rates:
        raise ValueError(f"Unknown model tier '{model}'. Expected one of: {list(rates)}")
    r = rates[model]
    input_rate = r["cache_read"] if cached else r["input"]
    cost = (input_tokens / 1_000_000) * input_rate + (output_tokens / 1_000_000) * r["output"]
    return round(cost, 4)


def summarize(stages: list[dict]) -> dict:
    """
    stages: list of {"name": str, "model": str, "input_tokens": int,
                      "output_tokens": int, "cached": bool (optional)}
    Returns per-stage cost plus total, sorted most expensive first.
    """
    results = []
    for s in stages:
        cost = estimate(s["model"], s["input_tokens"], s["output_tokens"], s.get("cached", False))
        results.append({**s, "cost_usd": cost})
    results.sort(key=lambda r: r["cost_usd"], reverse=True)
    total = round(sum(r["cost_usd"] for r in results), 4)
    return {"stages": results, "total_usd": total}


if __name__ == "__main__":
    if len(sys.argv) < 4:
        print(__doc__)
        sys.exit(1)
    model, in_tok, out_tok = sys.argv[1], int(sys.argv[2]), int(sys.argv[3])
    cached = "--cached" in sys.argv
    print(f"${estimate(model, in_tok, out_tok, cached):.4f}")
